
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velentine-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: valentine
  template:
    metadata:
      labels:
        app: valentine
    spec:
      containers:
        - name: valentine
          image: prashantritgit/valentine:v1 # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on

